require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false