version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: desconto_inss_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: desconto_inss
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
