version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: desconto_inss_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: desconto_inss
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data/redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  redis_data:
