default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'postgres') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'desconto_inss') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'desconto_inss_test') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'desconto_inss_production') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'desconto_inss_prod') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'desconto_inss_prod') %>